server:
  port: ${PORT:8080}
  shutdown: graceful

logging:
  file:
    name: logs/invoiceiq.log
  level:
    root: INFO
    com.grivetyglobals.invoiceiq: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n%ex"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n%ex"
spring:
  profiles:
    active: dev
  application:
    name: invoiceiq
  config:
    import: optional:file:.env[.properties], optional:file:ProjectIQBackend/.env[.properties]
  datasource:
    url: ${RENDER_DB_URL}
    username: ${RENDER_DB_USER}
    password: ${RENDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000
      connection-timeout: 10000
  data:
    redis:
      host: ${REDISHOST:localhost}
      port: ${REDISPORT:6379}
      password: ${REDISPASSWORD:}
      username: ${REDISUSER:}
      timeout: 5s
      connect-timeout: 5s
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  health:
    redis:
      enabled: false

jwt:
  secret: ${JWT_SECRET}

cloud:
  s3:
    endpoint-url: ${S3_ENDPOINT_URL}
    region: ${S3_REGION}
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY_ID}
    secret-key: ${S3_SECRET_ACCESS_KEY}
